/** Central registry of backend endpoint paths (relative to /api/v1). */
export const endpoints = {
  auth: {
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    me: "/auth/me",
    changePassword: "/auth/change-password",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
  },
  dashboard: {
    stats: "/dashboard/stats",
    charts: "/dashboard/charts",
    recentBookings: "/dashboard/recent-bookings",
    recentContacts: "/dashboard/recent-contacts",
    recentApplications: "/dashboard/recent-applications",
    activityLogs: "/dashboard/activity-logs",
  },
  users: {
    root: "/users",
    roles: "/users/roles/all",
    createRole: "/users/roles",
    role: (id: string) => `/users/roles/${id}`,
    permissions: "/users/permissions/all",
  },
  services: {
    root: "/services",
    categories: "/services/categories",
    category: (id: string) => `/services/categories/${id}`,
  },
  bookings: {
    root: "/bookings",
    export: "/bookings/export",
    approve: (id: string) => `/bookings/${id}/approve`,
    reject: (id: string) => `/bookings/${id}/reject`,
    cancel: (id: string) => `/bookings/${id}/cancel`,
    assign: (id: string) => `/bookings/${id}/assign`,
  },
  equipment: {
    root: "/equipment",
    categories: "/equipment/categories",
    category: (id: string) => `/equipment/categories/${id}`,
    rentals: "/equipment/rentals",
    rental: (id: string) => `/equipment/rentals/${id}`,
  },
  careers: {
    root: "/careers",
    categories: "/careers/categories",
    category: (id: string) => `/careers/categories/${id}`,
    applications: "/careers/applications",
    application: (id: string) => `/careers/applications/${id}`,
  },
  blogs: {
    root: "/blogs",
    categories: "/blogs/categories",
    category: (id: string) => `/blogs/categories/${id}`,
  },
  videos: { root: "/videos" },
  testimonials: { root: "/testimonials" },
  faqs: { root: "/faqs" },
  staff: { root: "/staff" },
  contact: { root: "/contact" },
  settings: {
    website: "/settings",
    social: "/settings/social",
    seo: "/settings/seo",
    seoAll: "/settings/seo/all",
  },
  notifications: {
    root: "/notifications",
    unread: "/notifications/unread-count",
    read: (id: string) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
  },
  uploads: {
    image: "/uploads/image",
    file: "/uploads/file",
    video: "/uploads/video",
    root: "/uploads",
  },
  search: "/search",
} as const;
